package io.github.christiangaertner.moebelplaner.menu.debug.items;

import io.github.christiangaertner.moebelplaner.Moebelplaner;
import io.github.christiangaertner.moebelplaner.grid.Grid;

/**
 *
 * @author Christian
 */
public class RenderSettingsWindow extends javax.swing.JPanel {

    private final Moebelplaner planer;
    private final Grid grid;

    /**
     * Creates new form TMP
     */
    public RenderSettingsWindow(Moebelplaner p, Grid g) {
        planer = p;
        grid = g;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JToggleButton();
        entites = new javax.swing.JToggleButton();
        highlights = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        bg.setSelected(grid.renderSettings("Background"));
        bg.setText("Background");
        bg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bgActionPerformed(evt);
            }
        });

        entites.setSelected(grid.renderSettings("Entity"));
        entites.setText("Entities");
        entites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entitesActionPerformed(evt);
            }
        });

        highlights.setSelected(grid.renderSettings("Highlight"));
        highlights.setText("Highlights");
        highlights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highlightsActionPerformed(evt);
            }
        });

        jLabel1.setText("Toogle Rendering");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel3.setText("RenderSettings");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(144, 144, 144)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel1)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                        .add(bg, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(entites, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(highlights, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 118, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .add(jLabel3)
                .add(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(28, 28, 28)
                .add(jLabel3)
                .add(31, 31, 31)
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(bg)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(entites)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(highlights)
                .addContainerGap(104, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bgActionPerformed
        grid.renderSettings("Background", !grid.renderSettings("Background"));
    }//GEN-LAST:event_bgActionPerformed

    private void entitesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entitesActionPerformed
        grid.renderSettings("Entity", !grid.renderSettings("Entity"));
    }//GEN-LAST:event_entitesActionPerformed

    private void highlightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highlightsActionPerformed
        grid.renderSettings("Highlight", !grid.renderSettings("Highlight"));
    }//GEN-LAST:event_highlightsActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton bg;
    private javax.swing.JToggleButton entites;
    private javax.swing.JToggleButton highlights;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
